config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :addresses, :except => [:show]
  resources :payments, :only => [:index, :new, :create]
  resources :venues, :only => [:show]
  # resources :users, :only => [:edit, :create, :update]

  root 'venues#index'

  # Static Pages
  match '/support', to: 'static_pages#support', :via => :get

  # get    '/account'   => 'sessions#show'
  # get    '/credits'   => 'sessions#credits'

  # Handle User & Sessions
  # get    'signup'  => 'users#new'
  # post   'signup'  => 'users#create'
  # post   'edit'    => 'users#edit'
  # get    'login'   => 'sessions#new'
  # post   'login'   => 'sessions#create'
  # get    'logout'  => 'sessions#destroy'
  # delete 'logout'  => 'sessions#destroy'

  
  match 'account', to: 'sessions#show', :via => :get
  match 'account/edit', to: 'users#edit', :via => :get
  match 'account/edit', to: 'users#update', :via => [:post, :patch]
  match 'credits', to: 'sessions#credits', :via => :get
  match 'signup', to: 'users#new', :via => :get
  match 'signup', to: 'users#create', :via => :post
  match 'login', to: 'sessions#new', :via => :get
  match 'login', to: 'sessions#create', :via => :post
  match 'logout', to: 'sessions#destroy', :via => [:get, :delete]
  match 'auth/:provider/callback', to: 'sessions#create_from_omniauth', :via => [:get, :post]
  match 'auth/failure', to: redirect('/'), :via => [:get, :post]

  # Handle Admin space
  match '/admin', to: 'admin#home', :via => 'get'  

  namespace :admin do
    resources :users
    resources :cities, :except => :show
    resources :merchants
    resources :venues do
      resources :product_groups, :except => :index, shallow: true do
        resources :products, :except => :index, shallow: true do
          resources :product_variations, :except => [:index, :show], shallow: true do
            resources :variation_options, :except => [:index, :show], shallow: true
          end
        end
      end
    end
  end

  # Release Candidate 2

  # namespace :api do
  #   resources :venues, :only => [:index, :show], format: 'json'
  # end

  # DEPRECATION GRAVEYARD

  
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  validates :business_name, presence: true
  has_many :venues, :dependent => :destroy
end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  before_action :set_merchant, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /admin/merchants
  def index
    @merchants = Merchant.all
  end

  # GET /admin/merchants/1
  def show
  end

  # GET /admin/merchants/new
  def new
    @merchant = Merchant.new
  end

  # GET /admin/merchants/1/edit
  def edit
  end

  # POST /admin/merchants
  def create
    @merchant = Merchant.new(merchant_params)
    if @merchant.save
      flash[:success] = "Merchant created"
      redirect_to admin_merchants_url
    else
      flash[:danger] = "Can't create merchant"
      render :new
    end
  end

  # PATCH/PUT /admin/merchants/1
  def update
    if @merchant.update(merchant_params)
      flash[:success] = "Merchant updated"
      redirect_to admin_merchants_url
    else
      flash[:danger] = "Can't update merchant"
      render :edit
    end
  end

  # DELETE /admin/merchants/1
  def destroy
    @merchant.destroy
    flash[:success] = "Merchant deleted"
    redirect_to admin_merchants_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_merchant
      @merchant = Merchant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def merchant_params
      params.require(:merchant).permit(:business_name, :business_id, :vat, :address, :city, :zip_code, :contact_person, :phone, :email)
    end
end

app/helpers/admin/merchants_helper.rb
module Admin::MerchantsHelper
end

app/views/admin/merchants/_form.html.erb
<%= form_for [:admin, merchant], :html => { class: 'form-horizontal' } do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= merchant.persisted? ? 'Edit' : ' New' %> Merchant</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label :business_name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :business_name , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :business_id, 'Business ID', class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :business_id , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :vat, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :vat , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :address, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :address , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :city, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :city , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :zip_code, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :zip_code , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :contact_person, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :contact_person , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :phone, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :phone , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.email_field :email , class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/merchants/edit.html.erb
<h1>
	Editing Merchant
	<%= link_to 'Show', admin_merchant_path(@merchant), class: 'btn btn-default' %>
</h1>

<%= render 'form', merchant: @merchant %>

app/views/admin/merchants/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Merchants</div>
  <table class="table">
    <tr>
      <th>Business</th>
      <th>City</th>
      <th>Contact Person</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Venues</th>
      <th></th>
    </tr>
    <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.business_name %> <%= "(#{merchant.business_id})" %></td>
        <td><%= merchant.city %></td>
        <td><%= merchant.contact_person %></td>
        <td><%= merchant.phone %></td>
        <td><a href="mailto:<%= merchant.email %>"><%= merchant.email %></a></td>
        <td><%= merchant.venues.count %></td>
        <td class="text-right">
          <%= link_to 'Show', admin_merchant_path(merchant), class: "btn btn-xs btn-default" %>
          <%= link_to 'Edit', edit_admin_merchant_path(merchant), class: "btn btn-xs btn-primary" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/merchants/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
	<%= render 'form', merchant: @merchant %>
</div>
	

app/views/admin/merchants/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading"><%= @merchant.business_name %> #<%= @merchant.id %></div>
  <div class="panel-body">
  	<p class="lead">Business ID</p>
  	<p><%= @merchant.business_id %></p>

  	<p class="lead">VAT</p>
  	<p><%= @merchant.vat %></p>

  	<p class="lead">Address</p>
  	<p><%= @merchant.address %><br/>
  	<%= "#{@merchant.zip_code} #{@merchant.city}" %></p>
  	
  	<p class="lead">Contact person</p>
  	<p><%= @merchant.contact_person %></p>
  	
  	<p class="lead">Phone</p>
  	<p><%= @merchant.phone %></p>
  	
  	<p class="lead">Email</p>
  	<p><a href="mailto:<%= @merchant.email %>"><%= @merchant.email %></a></p>
  </div>
  <div class="panel-heading">Venues</div>
  <table class="table">
    <tr>
      <th>#</th>
      <th>Status</th>
      <th>Name</th>
      <th></th>
    </tr>
    <% if @merchant.venues.each do |venue| %>
      <tr>
        <td><%= venue.id %></td>
        <td>
          <% if venue.editing? %>
            <span class="label label-default">editing</span>
          <% end %>
          <% if venue.live? %>
            <span class="label label-success">live</span>
          <% end %>
          <% if venue.offline? %>
            <span class="label label-danger">Offline</span>
          <% end %>
        </td>
        <td><%= venue.name %></td>
        <td class="text-right">
          <%= link_to 'Show', admin_venue_path(venue), class: "btn btn-xs btn-default" %>
          <%= link_to 'Edit', edit_admin_venue_path(venue), class: "btn btn-xs btn-primary" %>
        </td>
      </tr>
    <% end.empty? %>
      <tr><td colspan="4">No venues</td></tr>
    <% end %>
  </table>
  <div class="panel-footer">
  	<%= link_to 'Edit', edit_admin_merchant_path(@merchant), class: 'btn btn-primary'  %>
  	<%= link_to 'Destroy', admin_merchant_path(@merchant), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn  btn-danger" %>
  </div>
</div>