config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :addresses, :except => [:show]
  resources :payments, :only => [:index, :new, :create]
  resources :venues, :only => [:show]
  # resources :users, :only => [:edit, :create, :update]

  root 'venues#index'

  # Static Pages
  match '/support', to: 'static_pages#support', :via => :get

  # get    '/account'   => 'sessions#show'
  # get    '/credits'   => 'sessions#credits'

  # Handle User & Sessions
  # get    'signup'  => 'users#new'
  # post   'signup'  => 'users#create'
  # post   'edit'    => 'users#edit'
  # get    'login'   => 'sessions#new'
  # post   'login'   => 'sessions#create'
  # get    'logout'  => 'sessions#destroy'
  # delete 'logout'  => 'sessions#destroy'

  
  match 'account', to: 'sessions#show', :via => :get
  match 'account/edit', to: 'users#edit', :via => :get
  match 'account/edit', to: 'users#update', :via => [:post, :patch]
  match 'credits', to: 'sessions#credits', :via => :get
  match 'signup', to: 'users#new', :via => :get
  match 'signup', to: 'users#create', :via => :post
  match 'login', to: 'sessions#new', :via => :get
  match 'login', to: 'sessions#create', :via => :post
  match 'logout', to: 'sessions#destroy', :via => [:get, :delete]
  match 'auth/:provider/callback', to: 'sessions#create_from_omniauth', :via => [:get, :post]
  match 'auth/failure', to: redirect('/'), :via => [:get, :post]

  # Handle Admin space
  match '/admin', to: 'admin#home', :via => 'get'  

  namespace :admin do
    resources :users
    resources :cities, :except => :show
    resources :merchants
    resources :venues do
      resources :product_groups, :except => :index, shallow: true do
        resources :products, :except => :index, shallow: true do
          resources :product_variations, :except => [:index, :show], shallow: true do
            resources :variation_options, :except => [:index, :show], shallow: true
          end
        end
      end
    end
  end

  # Release Candidate 2

  # namespace :api do
  #   resources :venues, :only => [:index, :show], format: 'json'
  # end

  # DEPRECATION GRAVEYARD

  
end

app/models/product.rb
class Product < ApplicationRecord
  before_save :set_order
  validates :label, presence: true
  validates :base_price, presence: true
  validates :product_group_id, presence: true

  belongs_to :product_group
  has_many :product_variations, :dependent => :destroy

  enum status: [:live, :offline]

  def set_order
    unless self.order
      @next = Product.where(product_group_id: self.product_group_id).maximum("order")
      self.order = @next ? @next + 1 : 1;
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  layout 'admin'

  # GET /admin/products/1
  def show
  end

  # GET /admin/venues/1/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/1/edit
  def edit
  end

  # POST /admin/venues/1/products
  def create
    @product = Product.new(product_params)
    @product.product_group = ProductGroup.find(params[:product_group_id])

    if @product.save
      flash[:success] = 'Product was successfully created.'
      redirect_to admin_venue_url(@product.product_group.venue)
    else
      flash[:danger] = 'Product was *NOT* successfully created.'
      render :new
    end
  end

  # PATCH/PUT /admin/products/1
  def update
    if @product.update(product_params)
      flash[:success] = 'Product was successfully updated.'
      redirect_to admin_venue_url(@product.product_group.venue)
    else
      flash[:danger] = 'Product was *NOT* successfully updated.'
      render :edit
    end
  end

  # DELETE /admin/products/1
  def destroy
    @product.destroy
    redirect_to admin_venue_url(@product.product_group.venue)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:product_group_id, :label, :description, :base_price, :status, :order)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_action_buttons.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Actions</div>
  <div class="panel-body">
    <%= link_to 'Add Variation', new_admin_product_product_variation_path(@product), class: 'btn btn-default btn-block'  %>
    <%= link_to 'Edit', edit_admin_product_path(@product), class: 'btn btn-primary btn-block'  %>
    <%= link_to 'Destroy', admin_product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-block" %>
  </div>
</div>

app/views/admin/products/_details.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Product</div>
  <div class="panel-body">
    <p class="lead">
      <%= @product.label %>
      <% if @product.live? %>
        <span class="label label-success pull-right">live</span>
      <% end %>
      <% if @product.offline? %>
        <span class="label label-danger pull-right">Offline</span>
      <% end %>
    </p>
    <p><%= @product.description %></p>
    <p><%= @product.base_price %> CHF</p>
    
    <p>Venue: <%= link_to @product.product_group.venue.name, admin_venue_path(@product.product_group.venue) %></p>
    <p>Product Group: <%= link_to @product.product_group.label, admin_product_group_path(@product.product_group) %></p>
  </div>
</div>

app/views/admin/products/_form.html.erb
<%= form_for product.persisted? ? [:admin, product] : [:admin, :product_group, product], :html => { class: 'form-horizontal' } do |f| %>
<div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= product.persisted? ? 'Edit' : ' New' %> Product</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label :status, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.select(:status , Product.statuses.keys, {}, { :class => 'form-control' }) %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :label, class: 'col-sm-2 control-label' %> *
        <div class="col-sm-10">
          <%= f.text_field :label , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :description , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :order, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.number_field :order , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :base_price, class: 'col-sm-2 control-label' %> *
        <div class="col-sm-10">
          <%= f.number_field :base_price , class: 'form-control', step: :any %>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/products/_product_variations.html.erb
<% @product.product_variations.each do |product_variation| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <% if product_variation.allow_multi_choices? %>
        <span class="label label-success">Multi choice</span>
      <% else %>
        <span class="label label-success">Single choice</span>
      <% end %>

      <%= product_variation.label %>

      <div class="pull-right">
        <%= link_to 'Add variation option', new_admin_product_variation_variation_option_path(product_variation), class: "btn btn-xs btn-default" %>
        <%= link_to 'Edit', edit_admin_product_variation_path(product_variation), class: "btn btn-xs btn-primary" %> 
      </div>
    </div>

    <%= render 'variation_options', variation_options: product_variation.variation_options %>

  </div>
<% end %>

app/views/admin/products/_variation_options.html.erb
<table class="table" style="margin:0px;">
  <% unless variation_options.empty? %>
    <tr>
      <th>Label</th>
      <th>Price variation</th>
      <th>Allow multi choices</th>
      <th></th>
    </tr>
    <% variation_options.each do |variation_option| %>
      <tr>
        <td><%= variation_option.label %></td>
        <td><%= variation_option.price_variation %> CHF</td>
        <td>
          <%= variation_option.allow_multi_choices? ? 'yes' : 'no' %>
          
          <% if variation_option.allow_multi_choices? %>
            (limit <%= variation_option.multi_choice_limit %>)
          <% end %>
        </td>
        <td> </td>
        <td class="text-right">
          <%= link_to 'Edit', edit_admin_variation_option_path(variation_option), class: "btn btn-xs btn-primary" %>
        </td>
      </tr>
    <% end %>
  <% else %>
    <tr><td>Product variation empty</td></tr>
  <% end %>
</table>

app/views/admin/products/edit.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= render 'form', product: @product %>
</div>

app/views/admin/products/new.html.erb
<div class="col-sm-6 col-sm-offset-3">
  <%= render 'form', product: @product %>
</div>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= render 'details' %>
    <%= render 'action_buttons' %>
  </div>
  <div class="col-sm-9">
  <%= render 'product_variations' %>
  </div>
</div>