config/routes.rb
Rails.application.routes.draw do
  
  resources :orders
  resources :addresses, :except => [:show]
  resources :payments, :only => [:index, :new, :create]
  resources :venues, :only => [:show]
  # resources :users, :only => [:edit, :create, :update]

  root 'venues#index'

  # Static Pages
  match '/support', to: 'static_pages#support', :via => :get

  # get    '/account'   => 'sessions#show'
  # get    '/credits'   => 'sessions#credits'

  # Handle User & Sessions
  # get    'signup'  => 'users#new'
  # post   'signup'  => 'users#create'
  # post   'edit'    => 'users#edit'
  # get    'login'   => 'sessions#new'
  # post   'login'   => 'sessions#create'
  # get    'logout'  => 'sessions#destroy'
  # delete 'logout'  => 'sessions#destroy'

  
  match 'account', to: 'sessions#show', :via => :get
  match 'account/edit', to: 'users#edit', :via => :get
  match 'account/edit', to: 'users#update', :via => [:post, :patch]
  match 'credits', to: 'sessions#credits', :via => :get
  match 'signup', to: 'users#new', :via => :get
  match 'signup', to: 'users#create', :via => :post
  match 'login', to: 'sessions#new', :via => :get
  match 'login', to: 'sessions#create', :via => :post
  match 'logout', to: 'sessions#destroy', :via => [:get, :delete]
  match 'auth/:provider/callback', to: 'sessions#create_from_omniauth', :via => [:get, :post]
  match 'auth/failure', to: redirect('/'), :via => [:get, :post]

  # Handle Admin space
  match '/admin', to: 'admin#home', :via => 'get'  

  namespace :admin do
    resources :users
    resources :cities, :except => :show
    resources :merchants
    resources :venues do
      resources :product_groups, :except => :index, shallow: true do
        resources :products, :except => :index, shallow: true do
          resources :product_variations, :except => [:index, :show], shallow: true do
            resources :variation_options, :except => [:index, :show], shallow: true
          end
        end
      end
    end
  end

  # Release Candidate 2

  # namespace :api do
  #   resources :venues, :only => [:index, :show], format: 'json'
  # end

  # DEPRECATION GRAVEYARD

  
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :profile_picture, ProfilePictureUploader

  before_save { self.email = email.downcase if self.email}
  before_save :set_invitation_code

  after_create :create_stripe_customer
  after_save :check_stripe_customer
  
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: { case_sensitive: false }
  validates :phone, presence: true
  validates :password, length: { minimum: 6 }, :if => :password
  validates :invitation_code, :uniqueness => true
    
  validates_confirmation_of :password

  has_secure_password

  has_many :addresses

  attr_accessor :remember_token

  def check_stripe_customer
    unless stripe_id 
      create_stripe_customer
    end
  end

  def create_stripe_customer
    Stripe.api_key =  Rails.application.secrets.stripe_api_key
    @customer = Stripe::Customer.create(
      :description => name,
      :email => email,
      :metadata => {
      	:user_id => id
      }
    )
    update_attribute(:stripe_id, @customer.id)
  end

  def shown_addresses
    addresses.where(:status => :online)
  end
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.remote_profile_picture_url = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      pass = SecureRandom.uuid
      user.password = pass
      user.password_confirmation = pass
      user.save
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def generate_invitation_code
    [*('a'..'z'),*('0'..'9')].shuffle[0,4].join
  end

  def set_invitation_code
    if self.invitation_code.blank?
      loop do
        @code = generate_invitation_code.upcase
        break if User.where(invitation_code: @code).count == 0
      end
      self.invitation_code = @code
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_logged_in_user_only, :only => [:new]
  before_action :logged_in_user, :only => [:edit, :update]
  before_action :logged_in_user_and_fill_in, :except => [:edit, :new, :create, :update]

  layout 'account'

  def new
    @user = User.new()
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      remember(@user)
      redirect_to root_url
    else
      flash[:error] = 'Un problème est survenu. Merci de controller votre saisie.'
      render :new
    end
  end

  def update 
    @user = current_user
    if @user.update(user_params)
      redirect_to root_url
    else
      flash[:error] = 'Un problème est survenu. Merci de controller votre saisie.'
      render :edit
    end
  end

  private
    def user_params
      params.require(:user).permit(:profile_picture, :email, :password, :password_confirmation, :name, :phone, :referal)
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/users/_addresses.html.erb
<% @user.addresses.order(:status).each do |address| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <%= address.street %>
      <% if address.online? %>
        <span class="pull-right label label-success">online</span>
      <% else %>
        <span class="pull-right label label-danger">deleted</span>
      <% end %>
    </div>
    <div class="panel-body text-center">
      <% if address.latitude && address.longitude %>
      <img style="width:100%;" src="https://maps.googleapis.com/maps/api/staticmap?center=<%= address.latitude %>,<%= address.longitude %>&zoom=16&size=640x300&markers=<%= address.latitude %>,<%= address.longitude %>" />
      <% else %>
        latitude &amp; longitude missing
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/users/_form.html.erb
<%= form_for([:admin, user], :html => { :class => 'form-horizontal', :multipart => true }) do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= user.persisted? ? 'Edit' : ' New' %> User</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <%= f.label :name, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :name , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, class: 'col-sm-2 control-label' %> *
        <div class="col-sm-10">
          <%= f.email_field :email , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password, class: 'col-sm-2 control-label' %> *
        <div class="col-sm-10">
          <%= f.password_field :password, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, class: 'col-sm-2 control-label' %> *
        <div class="col-sm-10">
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :phone, class: 'col-sm-2 control-label' %> *
        <div class="col-sm-10">
          <%= f.text_field :phone , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :invitation_code, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.text_field :invitation_code , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :credits, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.number_field :credits , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :profile_picture, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <%= f.file_field :profile_picture , class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.check_box :admin %> <%= f.label :admin, class: ' control-label' %>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <%= f.submit class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Users</div>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Referral</th>
      <th>Stripe ID</th>
      <th>Orders</th>
      <th></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td>
          <%= user.name %>
          <% if user.admin? %>
            <span class="label label-success">admin</span>
          <% end %>
        </td>
        <td><%= link_to user.email, "mailto:#{user.email}" %></td>
        <td><%= link_to user.phone, "tel:#{user.phone}" %></td>
        <td><%= user.invitation_code %></td>
        <td><%= user.stripe_id %></td>
        <td>?</td>
        <td class="text-right">
          <%= link_to 'Show', admin_user_path(user), class: "btn btn-xs btn-default" %>
          <%= link_to 'Edit', edit_admin_user_path(user), class: "btn btn-xs btn-primary" %>
          <%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>